### ISSUE TITLE
 com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

### ISSUE THREAD

**Issue by shashi4414** [GoogleCloudPlatform/spark-recommendation-engine#13]
hi 
i'm following each step to configure spark recommendation engine in google cloud 
below step are completed 
created cloud platform project.
created  cluster in dataproc. 
created instance in google cloud sql.(first generation)
i have created database and table in mysql  cloud sql.
i try to  find best model through the dataproc i got jdbc connection error

 File "/tmp/433d1223-b139-4b58-8749-30bbf193eed6/find_model_collaborative.py", line 59, in <module>
    dfRates = sqlContext.read.jdbc(url=jdbcUrl, table='Rating')
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 475, in jdbc
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
**py4j.protocol.Py4JJavaError: An error occurred while calling o44.jdbc.

: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure**

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:418)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:632)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1016)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2194)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2225)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:418)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:61)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:52)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:58)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation.<init>(JDBCRelation.scala:113)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:47)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:306)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:146)
	at org.apache.spark.sql.DataFrameReader.jdbc(DataFrameReader.scala:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011)
	at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:567)
	... 33 more

please help me how to fix this problem

**Comment by danielreed** [comment]
Seeing the same issue, @shashi4414 did you ever resolve this?

**Comment by m-mayran** [comment]
Are you using the Dataproc or bdutil track?

**Comment by danielreed** [comment]
I'm using the Dataproc track.  I had a configuration problem, this is no longer an issue for me.

**Comment by shashi4414** [comment]
noo

**Comment by m-mayran** [comment]
Oopsie, apologies @shashi4414 . Thought you had it fixed as well.
Did you whitelist the IPs from the Dataproc instances so they can access Cloud SQL?
https://github.com/GoogleCloudPlatform/spark-recommendation-engine#create-and-configure-google-cloud-sql-first-generation-access

**Comment by shashi4414** [comment]
i triend it but issue is not solved.

**Comment by vibhorj** [comment]
Hi, facing same issue here, same error

Using:
- Cloud SQL (2nd generation)
- Dataproc
- (both within same Google Cloud Project, therefore I believe no need to whitelisting Dataproc IP instances within Cloud SQL authorizated network (?!), but still did that...

any clue will be highly appreciated!

Cheers!
